In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2025-12-08 14:58:38.714135: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
voc_size = 10000

In [4]:
one_hot_prer = [one_hot(words, voc_size) for words in sent]
one_hot_prer

[[7822, 7271, 9799, 1352],
 [7822, 7271, 9799, 8233],
 [7822, 2378, 9799, 3347],
 [2998, 4362, 7313, 3116, 2909],
 [2998, 4362, 7313, 3116, 3950],
 [1237, 7822, 3628, 9799, 5127],
 [523, 2729, 8982, 3116]]

In [5]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [7]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_prer, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7822 7271 9799 1352]
 [   0    0    0    0 7822 7271 9799 8233]
 [   0    0    0    0 7822 2378 9799 3347]
 [   0    0    0 2998 4362 7313 3116 2909]
 [   0    0    0 2998 4362 7313 3116 3950]
 [   0    0    0 1237 7822 3628 9799 5127]
 [   0    0    0    0  523 2729 8982 3116]]


In [8]:
dim = 10

In [9]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam', 'mse')

/Users/thanhchinhtran/Desktop/simple-RNN/venv/lib/python3.9/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 194ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 194ms/step


array([[[ 0.01690466, -0.0051955 , -0.03520655,  0.02095881,
          0.03078583, -0.03501095, -0.00675154,  0.04567932,
         -0.04715935,  0.03924514],
        [ 0.01690466, -0.0051955 , -0.03520655,  0.02095881,
          0.03078583, -0.03501095, -0.00675154,  0.04567932,
         -0.04715935,  0.03924514],
        [ 0.01690466, -0.0051955 , -0.03520655,  0.02095881,
          0.03078583, -0.03501095, -0.00675154,  0.04567932,
         -0.04715935,  0.03924514],
        [ 0.01690466, -0.0051955 , -0.03520655,  0.02095881,
          0.03078583, -0.03501095, -0.00675154,  0.04567932,
         -0.04715935,  0.03924514],
        [ 0.04814034, -0.04585752, -0.02165726, -0.03791492,
          0.04943614,  0.04338833, -0.04166975, -0.04405663,
         -0.00483445,  0.02015007],
        [ 0.03610906, -0.02702835, -0.04949919, -0.03018535,
         -0.03775425, -0.04050789,  0.00117408,  0.01081455,
          0.0085305 ,  0.03875115],
        [ 0.03298539,  0.01622707, -0.03247549, -0.0

In [12]:
embedded_docs[0]

array([   0,    0,    0,    0, 7822, 7271, 9799, 1352], dtype=int32)

In [13]:
model.predict(embedded_docs[0:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step


array([[[ 0.01690466, -0.0051955 , -0.03520655,  0.02095881,
          0.03078583, -0.03501095, -0.00675154,  0.04567932,
         -0.04715935,  0.03924514],
        [ 0.01690466, -0.0051955 , -0.03520655,  0.02095881,
          0.03078583, -0.03501095, -0.00675154,  0.04567932,
         -0.04715935,  0.03924514],
        [ 0.01690466, -0.0051955 , -0.03520655,  0.02095881,
          0.03078583, -0.03501095, -0.00675154,  0.04567932,
         -0.04715935,  0.03924514],
        [ 0.01690466, -0.0051955 , -0.03520655,  0.02095881,
          0.03078583, -0.03501095, -0.00675154,  0.04567932,
         -0.04715935,  0.03924514],
        [ 0.04814034, -0.04585752, -0.02165726, -0.03791492,
          0.04943614,  0.04338833, -0.04166975, -0.04405663,
         -0.00483445,  0.02015007],
        [ 0.03610906, -0.02702835, -0.04949919, -0.03018535,
         -0.03775425, -0.04050789,  0.00117408,  0.01081455,
          0.0085305 ,  0.03875115],
        [ 0.03298539,  0.01622707, -0.03247549, -0.0